### ISSUE TITLE
NoReverseMatch 

### ISSUE THREAD

**Issue by rcorzogutierrez** [mawimawi/datadjables#1]
NoReverseMatch at /

Reverse for '"datadjable_testing_person_list"' with arguments '()' and keyword arguments '{}' not found.

Error during template rendering
7   <li><a href="{% url "datadjable_testing_person_list" %}">Persons</a></li>

**Comment by mawimawi** [comment]
Yes, I knew, but thank you for noticing! I am at the moment tied on a different project, but during the next week I should be able to fix at least most of these annoying things and get the tests working again.

**Comment by mawimawi** [comment]
guess it's fixed now. at least the url `/persons` shows you a glimpse of what datadjables will be about.
