### ISSUE TITLE
error setup.py install

### ISSUE THREAD

**Issue by rcorzogutierrez** [mawimawi/datadjables#2]
When trying to install setup.py an error in the console
"error: can not copy 'datadjables \ static \ datadjables \ css \ ui-lightness': does not exist or not to regulate file"

**Comment by mawimawi** [comment]
Please ignore setup.py for the time being.

1st step: make sure that all packages in requirements.txt are installed in your environment (virtualenv should be best)
2nd step: `cd` into the datadjables directory where manage.py is located.
3rd step: python manage.py syncdb
4th step: python manage.py runserver
5th step: go to http://localhost:8000/persons/

The whole datadjables project as of right now (Oct. 2013) is in transition from a version which I have in a production environment to a very much overhauled version which is in alpha state and here on github.
